/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSourcesRouteImport } from './routes/_app.sources'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppOverviewRouteImport } from './routes/_app.overview'
import { Route as AppMetricsRouteImport } from './routes/_app.metrics'
import { Route as AppFunnelsRouteImport } from './routes/_app.funnels'
import { Route as AppForecastRouteImport } from './routes/_app.forecast'
import { Route as AppCohortsRouteImport } from './routes/_app.cohorts'
import { Route as AppAskRouteImport } from './routes/_app.ask'
import { Route as AppAlertsRouteImport } from './routes/_app.alerts'
import { Route as AppReportsIndexRouteImport } from './routes/_app.reports.index'
import { Route as AppSettingsAiRouteImport } from './routes/_app.settings.ai'
import { Route as AppReportsNewRouteImport } from './routes/_app.reports.new'
import { Route as AppReportsIdRouteImport } from './routes/_app.reports.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSourcesRoute = AppSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppOverviewRoute = AppOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AppRoute,
} as any)
const AppMetricsRoute = AppMetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => AppRoute,
} as any)
const AppFunnelsRoute = AppFunnelsRouteImport.update({
  id: '/funnels',
  path: '/funnels',
  getParentRoute: () => AppRoute,
} as any)
const AppForecastRoute = AppForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => AppRoute,
} as any)
const AppCohortsRoute = AppCohortsRouteImport.update({
  id: '/cohorts',
  path: '/cohorts',
  getParentRoute: () => AppRoute,
} as any)
const AppAskRoute = AppAskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsIndexRoute = AppReportsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppSettingsAiRoute = AppSettingsAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppReportsNewRoute = AppReportsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppReportsIdRoute = AppReportsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppReportsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AppAlertsRoute
  '/ask': typeof AppAskRoute
  '/cohorts': typeof AppCohortsRoute
  '/forecast': typeof AppForecastRoute
  '/funnels': typeof AppFunnelsRoute
  '/metrics': typeof AppMetricsRoute
  '/overview': typeof AppOverviewRoute
  '/reports': typeof AppReportsRouteWithChildren
  '/settings': typeof AppSettingsRouteWithChildren
  '/sources': typeof AppSourcesRoute
  '/reports/$id': typeof AppReportsIdRoute
  '/reports/new': typeof AppReportsNewRoute
  '/settings/ai': typeof AppSettingsAiRoute
  '/reports/': typeof AppReportsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AppAlertsRoute
  '/ask': typeof AppAskRoute
  '/cohorts': typeof AppCohortsRoute
  '/forecast': typeof AppForecastRoute
  '/funnels': typeof AppFunnelsRoute
  '/metrics': typeof AppMetricsRoute
  '/overview': typeof AppOverviewRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/sources': typeof AppSourcesRoute
  '/reports/$id': typeof AppReportsIdRoute
  '/reports/new': typeof AppReportsNewRoute
  '/settings/ai': typeof AppSettingsAiRoute
  '/reports': typeof AppReportsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/alerts': typeof AppAlertsRoute
  '/_app/ask': typeof AppAskRoute
  '/_app/cohorts': typeof AppCohortsRoute
  '/_app/forecast': typeof AppForecastRoute
  '/_app/funnels': typeof AppFunnelsRoute
  '/_app/metrics': typeof AppMetricsRoute
  '/_app/overview': typeof AppOverviewRoute
  '/_app/reports': typeof AppReportsRouteWithChildren
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/sources': typeof AppSourcesRoute
  '/_app/reports/$id': typeof AppReportsIdRoute
  '/_app/reports/new': typeof AppReportsNewRoute
  '/_app/settings/ai': typeof AppSettingsAiRoute
  '/_app/reports/': typeof AppReportsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/ask'
    | '/cohorts'
    | '/forecast'
    | '/funnels'
    | '/metrics'
    | '/overview'
    | '/reports'
    | '/settings'
    | '/sources'
    | '/reports/$id'
    | '/reports/new'
    | '/settings/ai'
    | '/reports/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/ask'
    | '/cohorts'
    | '/forecast'
    | '/funnels'
    | '/metrics'
    | '/overview'
    | '/settings'
    | '/sources'
    | '/reports/$id'
    | '/reports/new'
    | '/settings/ai'
    | '/reports'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/alerts'
    | '/_app/ask'
    | '/_app/cohorts'
    | '/_app/forecast'
    | '/_app/funnels'
    | '/_app/metrics'
    | '/_app/overview'
    | '/_app/reports'
    | '/_app/settings'
    | '/_app/sources'
    | '/_app/reports/$id'
    | '/_app/reports/new'
    | '/_app/settings/ai'
    | '/_app/reports/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/sources': {
      id: '/_app/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof AppSourcesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/overview': {
      id: '/_app/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AppOverviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/metrics': {
      id: '/_app/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof AppMetricsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/funnels': {
      id: '/_app/funnels'
      path: '/funnels'
      fullPath: '/funnels'
      preLoaderRoute: typeof AppFunnelsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/forecast': {
      id: '/_app/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof AppForecastRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cohorts': {
      id: '/_app/cohorts'
      path: '/cohorts'
      fullPath: '/cohorts'
      preLoaderRoute: typeof AppCohortsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ask': {
      id: '/_app/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AppAskRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alerts': {
      id: '/_app/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/': {
      id: '/_app/reports/'
      path: '/'
      fullPath: '/reports/'
      preLoaderRoute: typeof AppReportsIndexRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/_app/settings/ai': {
      id: '/_app/settings/ai'
      path: '/ai'
      fullPath: '/settings/ai'
      preLoaderRoute: typeof AppSettingsAiRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/reports/new': {
      id: '/_app/reports/new'
      path: '/new'
      fullPath: '/reports/new'
      preLoaderRoute: typeof AppReportsNewRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/_app/reports/$id': {
      id: '/_app/reports/$id'
      path: '/$id'
      fullPath: '/reports/$id'
      preLoaderRoute: typeof AppReportsIdRouteImport
      parentRoute: typeof AppReportsRoute
    }
  }
}

interface AppReportsRouteChildren {
  AppReportsIdRoute: typeof AppReportsIdRoute
  AppReportsNewRoute: typeof AppReportsNewRoute
  AppReportsIndexRoute: typeof AppReportsIndexRoute
}

const AppReportsRouteChildren: AppReportsRouteChildren = {
  AppReportsIdRoute: AppReportsIdRoute,
  AppReportsNewRoute: AppReportsNewRoute,
  AppReportsIndexRoute: AppReportsIndexRoute,
}

const AppReportsRouteWithChildren = AppReportsRoute._addFileChildren(
  AppReportsRouteChildren,
)

interface AppSettingsRouteChildren {
  AppSettingsAiRoute: typeof AppSettingsAiRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsAiRoute: AppSettingsAiRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteChildren {
  AppAlertsRoute: typeof AppAlertsRoute
  AppAskRoute: typeof AppAskRoute
  AppCohortsRoute: typeof AppCohortsRoute
  AppForecastRoute: typeof AppForecastRoute
  AppFunnelsRoute: typeof AppFunnelsRoute
  AppMetricsRoute: typeof AppMetricsRoute
  AppOverviewRoute: typeof AppOverviewRoute
  AppReportsRoute: typeof AppReportsRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppSourcesRoute: typeof AppSourcesRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlertsRoute: AppAlertsRoute,
  AppAskRoute: AppAskRoute,
  AppCohortsRoute: AppCohortsRoute,
  AppForecastRoute: AppForecastRoute,
  AppFunnelsRoute: AppFunnelsRoute,
  AppMetricsRoute: AppMetricsRoute,
  AppOverviewRoute: AppOverviewRoute,
  AppReportsRoute: AppReportsRouteWithChildren,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppSourcesRoute: AppSourcesRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
